Application UI base
1alexandra/collage pull request #6
Opened 2020-03-19 17:50 UTC by 1alexandra

layout.py:
class Application constructing main window is added.
class TextConfigureApp constructing text configuring window is added.
Text redactor, text color chooser and text font choosed is added.
run.py:
running Application

2020-03-21 12:20 UTC, Satbek requested changes

2020-03-21 12:20 UTC, Satbek commented on collage/layout.py
> +from datetime import datetime
When we are packing application, we have only python3.7, python3.8 builtin libraries. Please add additional libraries to requirements.txt, and write tests for components which use them.

2020-03-21 12:20 UTC, Satbek commented on collage/layout.py
> +    return np.unique(fonts)
move this function to some module and test it

2020-03-21 12:20 UTC, Satbek commented on collage/layout.py
> +    def create_widgets(self):
Add additional methods to initialise some widgets. This method is too big, and I think it should be separated.

2020-03-21 12:20 UTC, Satbek commented on collage/layout.py
> +class TextConfigureApp(tk.Frame):
move this class to another file

2020-03-21 12:20 UTC, Satbek commented on collage/layout.py
> +        print(self.rgb, self.color_name)
I think it would be better for logging
https://docs.python.org/3/library/logging.html

2020-03-21 12:20 UTC, Satbek commented on collage/run.py
> +from layout import *
Is it necessary?

2020-03-21 12:20 UTC, Satbek commented on collage/layout.py
> +    def create_widgets(self):
Separate this method for:
* create_text_redactor
* create_font_chooser
* and so on

2020-03-25 21:08 UTC, Satbek approved these changes

2020-03-25 22:16 UTC, krchmark commented on collage/fonts.py
> +    return np.unique(fonts)
In my opinion, `set(fonts)` fits better here. `np.unique` is more for numerical types.

2020-03-25 23:40 UTC, krchmark reviewed
Not finished yet, but there are some comments for now:
1) There are a lot of constants that defined right in the code. Not sure if it is okay.
2) Some parts are not so easy to understand. We should use more commentaries in the code.
3) Ideally interface should be totally customizable somewhere from the outside (including grid generation). But let's keep it for a better day.

2020-03-25 23:40 UTC, krchmark commented on collage/fonts.py
> +        slash = x.find('\\')
Are we supporting Linux?

2020-03-25 23:40 UTC, krchmark commented on collage/grid.py
> +def grid_frame(frame, frame_rows=[0], frame_cols=[0], origin_row=0, origin_column=0, origin_sticky='snwe'):
Do we really need to receive a list here? Wouldn't a tuple of first and last rows be enough?

2020-03-25 23:40 UTC, krchmark commented on collage/mainwindow.py
> +        grid_frame(self.master, [0], [0], None, None, None)
I think, you should use keyword arguments here to increase readability.

2020-03-25 23:40 UTC, krchmark commented on collage/mainwindow.py
> +        self.undo_button = tk.Button(buttons_frame, text='Undo', width=bw)
I think, we should define all these constant strings in some yaml/json.

2020-03-25 23:40 UTC, krchmark commented on collage/mainwindow.py
> +        self.width_label = tk.Label(entries_frame, text="Width in pixels", padx=px)
Same about constant strings.

2020-03-25 23:40 UTC, krchmark commented on collage/mainwindow.py
> +        self.save2_button = tk.Button(buttons_frame, text='Save as...', width=bw)
Non-informative name of variable

2020-03-25 23:40 UTC, krchmark commented on collage/mainwindow.py
> +        self.save2_button = tk.Button(buttons_frame, text='Save as...', width=bw)
Also, not sure if it is a good idea to define a variable for every button

2020-03-25 23:40 UTC, krchmark commented on collage/mainwindow.py
> +        self.text_button = tk.Button(text_button_frame, text="Add text...", padx=5, pady=5)
It is a good practice to initialize all the fields in constructor, just to understrand what are variables we are dealing with

2020-03-26 08:26 UTC, 1alexandra commented on collage/grid.py
> +def grid_frame(frame, frame_rows=[0], frame_cols=[0], origin_row=0, origin_column=0, origin_sticky='snwe'):
No. Here we define which rows/columns of frame will be stretchable. It is possible, that we don't want it to be neighboring.

2020-03-26 14:52 UTC, Satbek commented on collage/fonts.py
> +        slash = x.find('\\')
yes

2020-03-26 19:53 UTC, krchmark commented on requirements.txt
> +numpy==1.18.2
Not used anymore

2020-03-27 07:43 UTC, merged